# This is a basic workflow to help you get started with Actions

name: React Build

# Controls when the workflow will run
on: [ pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      # Runs a single command using the runners shell
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
